### ISSUE TITLE
Logging in to web platforms

### ISSUE THREAD

**Issue by dennythepilgrim** [thiago-dev/fivem-hypnonema#11]
It is nice to watch free YouTube videos and all, but could there be a way to log into platforms, and watch stuff like Netflix, or Hulu? Or even purchased videos/movies on YouTube?

An option could be to have a config file, which would allow someone to put in login credentials, and the resource authenticates it based on whichever platform it is.

**Comment by thiago-dev** [comment]
There is currently no easy way to accomplish this task (external login -> social oauth), by not compromising security, I am aware of. (the content inside cef browser is actually an iframe) But an alternative solution to your desired goal could be a rtmp server (which supports MPEG-DASH) where you stream the file/desktop to, so that you can use the script to play it back. (for a no-cost solution see nginx-rtmp).
